#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
# Split the string by spaces to keep track of multiple spaces
    words = s.split(' ')
    
    # Capitalize only the first letter of each individual segment
    capitalized_words = [word.capitalize() for word in words]
    
    # Join them back together with a single space
    return ' '.join(capitalized_words)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
